### ISSUE TITLE
Demo App Not Running

### ISSUE THREAD

**Issue by balajibabugangadharan** [PayBy/PayBy-inApp-iOS#1]
<img width="876" alt="Screenshot 2020-10-26 at 1 27 29 PM" src="https://user-images.githubusercontent.com/24794204/97147118-01081080-178f-11eb-82a2-73a8d72fe0bd.png">

Can't able to run. Please check

**Comment by yangbukang** [comment]
SLDPayByPayment.framework only supports debugging on iPhone device, and does not support running on simulator, please run on iPhone device

**Comment by balajibabugangadharan** [comment]
Thanks for your immediate support
